<a href="https://colab.research.google.com/github/rajiv1817/NLP/blob/main/NLP_word_2_vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

122010304017-Rajiv

In [1]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense

In [2]:
reviews =[
          'worst experience',
          'Awful service',
          'bad waitress',
          'spoiled food',
          'Disappointing food',
          'great experience',
          'execellent service',
          'beautiful waitress',
          'tasty food',
          'healthy food!'
]

In [3]:
labels = array([1,1,1,1,1,0,0,0,0,0])

In [4]:
Vocab_size = 40
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[20, 3], [8, 6], [16, 18], [10, 7], [38, 7], [34, 3], [16, 6], [29, 18], [26, 7], [16, 7]]


In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[20  3  0]
 [ 8  6  0]
 [16 18  0]
 [10  7  0]
 [38  7  0]
 [34  3  0]
 [16  6  0]
 [29 18  0]
 [26  7  0]
 [16  7  0]]


In [6]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=5,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              200       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 216 (864.00 Byte)
Trainable params: 216 (864.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [7]:
model.fit(padded_reviews, labels, epochs=30)

Epoch 1/30
1/1 [==============================] - 1s 874ms/step - loss: 0.6930 - acc: 0.5000
Epoch 2/30
1/1 [==============================] - 0s 18ms/step - loss: 0.6923 - acc: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 12ms/step - loss: 0.6915 - acc: 0.5000
Epoch 4/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6908 - acc: 0.6000
Epoch 5/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6901 - acc: 0.5000
Epoch 6/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6893 - acc: 0.5000
Epoch 7/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6886 - acc: 0.5000
Epoch 8/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6879 - acc: 0.5000
Epoch 9/30
1/1 [==============================] - 0s 12ms/step - loss: 0.6871 - acc: 0.6000
Epoch 10/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6864 - acc: 0.8000
Epoch 11/30
1/1 [==============================] - 0s 14ms/step - loss: 0.6857

In [8]:
modelloss, modelaccuracy = model.evaluate(padded_reviews, labels, verbose=0)
print('Accuracy: %f' % (modelaccuracy*100))

Accuracy: 89.999998
